version: '3'

services:
    backend:
        container_name: express35
        restart: always
        build: .
        networks:
          - our-library-net
        ports:
            - 10035:5535
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules

        command: npm run dev
        stdin_open: true 
        tty: true

        environment:
          - DB_USER=Jameskodemia
          - DB_PASSWORD=Jameskodemia
          - DB_HOST=jeffrybezoskodemia.uzveq.mongodb.net
          - DB_NAME=dbenroute
          - JWT_SECRET=supersecret

networks:
  our-library-net:
    external: true
    driver: bridge